# Generated by Django 5.0.7 on 2024-08-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carinventory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carinventory',
            table='car_inventory',
        ),
    ]
